package synthesizer

import (
	"math"
	"time"

	"github.com/zetetos/simtezilo/app/calibrator"
)

// MockMixer implements MixerInterface for testing.
// When calibration is enabled, it generates a sine wave in MixToMaster.
type MockMixer struct {
	calibrator  calibrator.Calibrator
	sampleRate  int
	phase       float64
	lastSamples []float64 // samples generated by MixToMaster
}

// NewMockMixer creates a new MockMixer instance.
func NewMockMixer(sampleRate int, cal calibrator.Calibrator) *MockMixer {
	return &MockMixer{
		calibrator: cal,
		sampleRate: sampleRate,
	}
}

func (m *MockMixer) MixToMaster(length int) {
	m.lastSamples = make([]float64, length)

	if m.calibrator != nil && m.calibrator.IsEnabled() {
		freq := m.calibrator.GetFrequency()
		gainDB := m.calibrator.GetGain()
		gain := GainToPowerRatio(gainDB)

		for i := range m.lastSamples {
			m.lastSamples[i] = math.Sin(m.phase) * gain
			m.phase += 2 * math.Pi * freq / float64(m.sampleRate)

			if m.phase > 2*math.Pi {
				m.phase -= 2 * math.Pi
			}
		}
	}
}

func (m *MockMixer) ReadChannel(_ string, length int) []float64 {
	if len(m.lastSamples) == 0 {
		return make([]float64, length)
	}

	return m.lastSamples
}

func (m *MockMixer) AddChannel(_ string, _ float64) error {
	return nil
}

func (m *MockMixer) GetChannelGain(_ string) (float64, error) {
	return 0, nil
}

func (m *MockMixer) SetChannelGain(_ string, _ float64) error {
	return nil
}

func (m *MockMixer) GetChannelPowerRatio(_ string) (float64, error) {
	return 1, nil
}

func (m *MockMixer) WriteChannel(_ string, _ []float64, _ float64, _ int, _ bool) error {
	return nil
}

func (m *MockMixer) ClearChannelBuffer(_ string) {}

func (m *MockMixer) ClearBuffers() {}

func (m *MockMixer) InspectChannelBuffer(_ string, _ int, _ int) []float64 {
	return nil
}

func (m *MockMixer) GetBufferCapacity() int {
	return 0
}

func (m *MockMixer) FadeIn(_ time.Duration) {}

func (m *MockMixer) SetFader(_ float64) {}

func (m *MockMixer) ResetSineWavePhase() {}

func (m *MockMixer) Close() {}

func (m *MockMixer) GetChannelMute(_ int) bool {
	return false
}

func (m *MockMixer) GetMasterMute() bool {
	return false
}

func (m *MockMixer) SetSilenced(bool) {}
